adding notification contextualisation support
CriminalInjuriesCompensationAuthority/q-templates-application pull request #108
Opened 2022-03-01 09:36 UTC by neil-stephen-mcgonigle

contextualised template ids used in place of body content.

2022-03-01 09:58 UTC, neil-stephen-mcgonigle commented
Having a think about version bump

2022-03-01 11:25 UTC, armoj requested changes

2022-03-01 11:42 UTC, neil-stephen-mcgonigle commented on src/template.js
> +                sendEmail: {
https://github.com/CriminalInjuriesCompensationAuthority/q-templates-application/blob/72ec67042ab22ff3592e06c9ccfdd7bb33d3170c/index.js#L13339

2022-03-01 11:42 UTC, neil-stephen-mcgonigle commented on src/template.js
> +                sendEmail: {
My branch is built upon your original notifications branch, for reference.

2022-03-01 11:47 UTC, neil-stephen-mcgonigle commented on src/lib/deleteKeys.js
> +    // meta tasks do not have unwantedKeys at the moment
neither do I, but I didn't write it :)

2022-03-01 14:06 UTC, neil-stephen-mcgonigle commented on src/lib/deleteKeys.test.js
> +    it('should strip the current templaate of the provided nested keys and return expected properties', () => {
fixed

2022-03-01 14:19 UTC, neil-stephen-mcgonigle commented on src/template.js
> +                sendEmail: {
leaving this as is for now.

2022-03-03 10:06 UTC, neil-stephen-mcgonigle commented on src/lib/deleteKeys.js
> +    // meta tasks do not have unwantedKeys at the moment
added explicit null and undefined checks

2022-03-03 11:08 UTC, BarryPiccinni approved these changes
Approved, but it's a bit of a concern that you were able to make this change and not have to update the q-schema module. The validation of the `meta` section is probably too loose.

2022-03-08 16:40 UTC, armoj commented
is [this commit](e5d6b4e4f43a804090ba3993e8d24d00e1e381c6) now redundant due to Barry's updates?

2022-03-10 08:30 UTC, merged