Bug/cds2 185/deceased journey routing fix
CriminalInjuriesCompensationAuthority/q-templates-application pull request #217
Opened 2023-06-05 13:13 UTC by tjbburton

- Remove loop involving crime reference number

The issue was caused by the applicant being asked which police force is investigating the crime even if they previously said the crime had not been reported to the police. Now, if the crime was not reported to the police, the police force question and subsequent reference number questions are skipped.

2023-06-05 13:18 UTC, neil-stephen-mcgonigle requested changes
Notice the discrepancies in this PR.
58 commits and 47 files changed. 
To resolve this rebase deceased-journey, it is up to date with master, against your branch then force push your branch which will update this PR and only your changes should be displayed.

2023-06-06 12:49 UTC, stephenjmcneill1971 commented on src/lib/resource/sections/applicant-where-in-england-did-it-happen.js
> +                    cond: [
Change to use deceased role for routing

2023-06-06 12:49 UTC, stephenjmcneill1971 commented on src/lib/resource/sections/applicant-where-in-england-did-it-happen.js
> +                        ['==', '$.answers.p-applicant-fatal-claim.q-applicant-fatal-claim', true],
Change to use deceased role for routing

2023-06-06 12:49 UTC, stephenjmcneill1971 commented on src/lib/resource/sections/applicant-where-in-scotland-did-it-happen.js
> +                    cond: [
Change to use deceased role for routing

2023-06-06 12:49 UTC, stephenjmcneill1971 commented on src/lib/resource/sections/applicant-where-in-wales-did-it-happen.js
> +                    cond: [
Change to use deceased role for routing

2023-06-06 12:49 UTC, stephenjmcneill1971 commented on src/lib/resource/sections/applicant-where-in-wales-did-it-happen.js
> +                        ['==', '$.answers.p-applicant-fatal-claim.q-applicant-fatal-claim', true],
Change to use deceased role for routing

2023-06-06 14:35 UTC, tjbburton commented on src/lib/resource/sections/applicant-where-in-england-did-it-happen.js
> +                    cond: [
Roles added

2023-06-06 14:35 UTC, tjbburton commented on src/lib/resource/sections/applicant-where-in-scotland-did-it-happen.js
> +                    cond: [
Roles added

2023-06-06 14:36 UTC, tjbburton commented on src/lib/resource/sections/applicant-where-in-wales-did-it-happen.js
> +                        ['==', '$.answers.p-applicant-fatal-claim.q-applicant-fatal-claim', true],
Roles added

2023-06-06 15:01 UTC, stephenjmcneill1971 approved these changes

2023-06-09 10:51 UTC, neil-stephen-mcgonigle approved these changes

2023-06-09 10:51 UTC, stephenjmcneill1971 approved these changes

2023-06-09 10:51 UTC, merged