[CDBT] - Template Updates
CriminalInjuriesCompensationAuthority/q-templates-application pull request #273
Opened 2023-08-31 14:15 UTC by jack-burt-is

Covers bug fixes and enhancements including:
- [[CDBT-185] - Split Applications Email Templates](https://dsdmoj.atlassian.net/browse/CDBT-185)
- [[CDBT-149] - Multiple CRN Confirmation](https://dsdmoj.atlassian.net/browse/CDBT-149)
- [[CDBT-201] - Hide under 18 on Summary](https://dsdmoj.atlassian.net/browse/CDBT-201)

2023-09-04 10:16 UTC, neil-stephen-mcgonigle commented
Jack are these changes backwards compatible with data capture service?
![image](https://github.com/CriminalInjuriesCompensationAuthority/q-templates-application/assets/41323244/4910b142-3470-4ce9-bc6d-a68c6a782fed)

2023-09-04 10:24 UTC, jack-burt-is commented
> @jack-burt-is are these changes backwards compatible with data capture service? ![image](https://user-images.githubusercontent.com/41323244/265428980-4910b142-3470-4ce9-bc6d-a68c6a782fed.png)

They should all be backwards compatible yes, so a minor version is likely most appropriate

2023-09-04 10:28 UTC, neil-stephen-mcgonigle requested changes

2023-09-04 10:28 UTC, neil-stephen-mcgonigle commented on src/lib/resource/sections/applicant-are-you-18-or-over.js
> +                                },
unnecessary comma

2023-09-04 10:46 UTC, neil-stephen-mcgonigle approved these changes

2023-09-04 10:51 UTC, neil-stephen-mcgonigle commented
@jack-burt-is there are failing tests.

2023-09-04 10:56 UTC, neil-stephen-mcgonigle requested changes
Failing tests

2023-09-12 07:31 UTC, neil-stephen-mcgonigle commented
- already merged to master

2023-09-12 07:31 UTC, closed without merging